# Generated by Django 3.1.7 on 2021-03-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210327_0202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Author1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
