# Generated by Django 3.1.7 on 2021-03-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210327_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author1',
            new_name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='api.Author'),
        ),
    ]
