# Generated by Django 3.1.7 on 2021-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210327_0203'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(db_tablespace='name', fields=['name'], name='api_author_name_076641_idx'),
        ),
    ]
