# Generated by Django 3.1.7 on 2021-04-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210402_2048'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['id'], name='api_book_id_55821a_idx'),
        ),
    ]
