# Generated by Django 3.1.7 on 2021-04-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210402_2112'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='api_book_id_55821a_idx',
        ),
    ]
